### ISSUE TITLE
小米4 手机上 怎么没有还可以回到原来的位置的效果呢

### ISSUE THREAD

**Issue by tianshaokai** [oxoooo/pull-back-layout#1]

**Comment by xingrz** [comment]
~~Shared Element Transition 需要 Android 5.0 以上系统的支持。~~

Shared Element Transition 是要你自己做的，不在 PullBackLayout 的范畴内。

**Comment by tianshaokai** [comment]
谢谢，希望还可以兼容低版本的系统，就太好了

**Comment by xingrz** [comment]
PullBackLayout 本身是可以兼容到 2.X 的。Shared Element Transition 是要你自己做的，不在 PullBackLayout 的范畴内。
